#!/usr/bin/env bash

bash gradlew plugin && sudo unzip -o build/distributions/elasticsearch-image-2.4.1.zip -d /usr/share/elasticsearch/plugins/elasticsearch-image-2.4.1/ && sudo service elasticsearch restart
